"""Editorial direction for each product, independent of its store description."""

# variant, accent, paper, ink, Korean headline, English headline, bilingual highlights
PROFILES = {
    "dday-lite": ("memory", "#a74468", "#fff7f5", "#3e2831", "기다리는 날도,\n기억하는 날도.", "Days to anticipate.\nDays to remember.", [("D-Day와 D+", "Count down & count up"), ("사진으로 꾸미는 카드", "Personal photo cards"), ("홈 화면 위젯", "Home screen widgets")]),
    "why-am-i-paying": ("ledger", "#2559bd", "#f3f6fb", "#192b46", "매달 나가는 돈,\n한눈에.", "Your subscriptions.\nIn plain sight.", [("월간·연간 결제 관리", "Monthly & annual payments"), ("결제 캘린더", "Payment calendar"), ("결제 전 알림", "Payment reminders")]),
    "emotion-calendar": ("journal", "#79549d", "#faf5fc", "#3c304a", "오늘의 마음에\n작은 표시 하나.", "A small mark\nfor how you feel.", [("하루 한 번 감정 기록", "A mood a day"), ("달력으로 돌아보기", "Look back on your calendar"), ("나만의 감정 캐릭터", "Your own mood characters")]),
    "before-forget": ("planner", "#a24b17", "#fff9ef", "#3c3229", "생각났을 때 적고,\n잊기 전에 알림.", "Save the thought.\nCatch the moment.", [("빠른 일정 등록", "Quick schedule entry"), ("오늘·주간·월간 보기", "Daily, weekly & monthly views"), ("홈 화면 위젯", "Home screen widgets")]),
    "reptile-note": ("field", "#386441", "#f1f3e9", "#27382b", "작은 기록이 모여,\n더 세심한 돌봄.", "Small observations.\nThoughtful care.", [("동물과 사육장별 기록", "Animals & enclosures"), ("급여·온습도·체중", "Feeding, climate & weight"), ("캘린더와 타임라인", "Calendar & timeline")]),
    "secret-shelf": ("library", "#84522f", "#f6efe2", "#392c22", "읽은 책이 쌓여,\n나만의 서재가 되다.", "One book at a time.\nA library of your own.", [("표지와 책등으로 보기", "Covers & book spines"), ("월간 독서 엽서", "Monthly reading postcards"), ("연간 독서 통계", "Your reading year")]),
    "learnquest-jlpt": ("quest", "#e8b950", "#171d29", "#f4ebd8", "오늘의 일본어,\n퀘스트로 시작.", "Your next Japanese\nquest starts here.", [("N5부터 N1까지", "From N5 to N1"), ("한자·어휘·문법 전투", "Kanji, vocabulary & grammar"), ("틀린 문제 다시 도전", "Revisit missed questions")]),
    "gongbok-switch": ("wellness", "#3c715d", "#f2f7ed", "#243c32", "나에게 맞는 리듬,\n오늘도 가볍게.", "Find your rhythm.\nOne day at a time.", [("목표 공복 타이머", "Fasting goal timer"), ("오늘의 루틴 체크", "Daily routine checklist"), ("주간 기록 돌아보기", "Weekly trends")]),
    "my-travel-pins": ("atlas", "#176b87", "#eef6f5", "#203f49", "다녀온 곳마다,\n나만의 지도.", "Every place visited.\nA map of your own.", [("나라와 도시 기록", "Countries & cities"), ("여행 경로와 통계", "Routes & travel stats"), ("지도 이미지 공유", "Share your map")]),
    "gym-again-today": ("training", "#b8ee58", "#141916", "#f1f5ed", "한 세트 더.\n기록은 짧게.", "One more set.\nLess time logging.", [("세트 버튼으로 기록", "Tap to log a set"), ("자동 휴식 타이머", "Automatic rest timer"), ("루틴과 운동 통계", "Routines & workout stats")]),
    "worldcup-if-coach": ("stadium", "#b6f06a", "#10271f", "#f0f7ec", "선발부터 마지막 교체까지.\n이번엔 내가 감독.", "Pick the team.\nMake the call.", [("선발과 포메이션", "Lineups & formations"), ("경기 중 전술 변경", "Live tactical changes"), ("감독 판단 리포트", "Manager decision report")]),
    "zigzag-rabbit": ("playful", "#ab354f", "#fff3ed", "#462732", "톡, 방향을 바꾸고.\n조금만 더 멀리.", "Tap. Turn.\nGo a little further.", [("원터치 조작", "One-touch controls"), ("지그재그 아케이드", "Zigzag arcade"), ("로우폴리 그래픽", "Low-poly graphics")]),
    "planet-game": ("cosmos", "#c4b0ff", "#14162e", "#f2edff", "작은 행성 둘,\n더 큰 우주 하나.", "Small planets.\nBigger possibilities.", [("행성을 충돌시키고", "Collide planets"), ("더 큰 행성을 만들고", "Make bigger planets"), ("다음 한 수를 생각하고", "Plan your next move")]),
    "1010": ("blocks", "#2b64a0", "#f3f8fc", "#20384c", "열 칸, 열 줄.\n다음 블록은 어디에?", "Ten by ten.\nWhere next?", [("10 × 10 보드", "10 × 10 board"), ("블록 배치 퍼즐", "Block placement puzzle"), ("가로·세로 줄 완성", "Complete rows & columns")]),
    "lllilll": ("type", "#172d38", "#f5f4e9", "#172d38", "lllilll\n다른 하나가 보이나요?", "lllilll\nSpot the odd one.", [("20초의 집중", "20 seconds to focus"), ("닮은 알파벳", "Look-alike letters"), ("다른 글자 찾기", "Find the different letter")]),
    "fruit-sandwich": ("picnic", "#a44733", "#fff6e5", "#4b342a", "샌드위치 준비됐어요.\n순서대로 담아주세요!", "Sandwiches are ready.\nPack them in order!", [("상자 속 순서 확인", "Check the order"), ("샌드위치 선택", "Choose your sandwiches"), ("브라우저에서 플레이", "Play in your browser")]),
    "prism-horn": ("neon", "#95e6ed", "#131327", "#f3eeff", "색을 맞추고,\n무지개로 막아라.", "Match the color.\nHold the rainbow.", [("색과 모양을 맞춘 공격", "Match colors & shapes"), ("레벨마다 강화 선택", "Choose upgrades"), ("js13kGames 2026", "js13kGames 2026")]),
    "grass-tower-defense": ("terminal", "#9be275", "#112419", "#e4f2df", "오늘의 잔디밭을\n지켜주세요.", "Defend your\ncontribution garden.", [("기여 포인트 모으기", "Earn contribution points"), ("타워를 세워 방어", "Build your defenses"), ("js13kGames 2025", "js13kGames 2025")]),
    "13-maze": ("maze", "#e6cf6e", "#202423", "#f0eedf", "13을 넘지 말 것.\n출구를 찾을 것.", "Stay within thirteen.\nFind the way out.", [("타일을 눌러 이동", "Click tiles to move"), ("점수를 관리하는 미로", "Keep your score in balance"), ("js13kGames 2024", "js13kGames 2024")]),
    "13c-defense": ("castle", "#dec591", "#292620", "#f3eddf", "성문에 닿기 전에,\n진격을 막아라.", "Hold the path.\nDefend the gate.", [("13세기 전투에서 영감", "Inspired by medieval battles"), ("경로를 따라오는 적", "Enemies on a set path"), ("js13kGames 2023", "js13kGames 2023")]),
    "death-scythe": ("shadow", "#d6a9ed", "#1a1620", "#f1e8f6", "로프를 걸고,\n어둠 너머로.", "Cast your rope.\nSwing into the dark.", [("마우스 클릭으로 이동", "Move with mouse clicks"), ("횡스크롤 러닝", "Side-scrolling runner"), ("js13kGames 2022", "js13kGames 2022")]),
}
